#ifndef COMMON_H
#define COMMON_H

enum ATTRIB_ID {
  ATTRIB_POSITIONS = 0,
  ATTRIB_NORMALS = 1,
  ATTRIB_COLOR_TEXTURE_COORDS = 2
};

enum TEXTURE_UNIT_ID { TEXTURE_COLOR = 0 };

enum APP_STATE { VIEWPORT_FOCUS, MENU_CONTROL, FREEZE };

#endif  // COMMON_H
