name: Build project on Windows

on: [push, workflow_dispatch]

# for vcpkg cache
env: 
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [windows-msvc-release, windows-clangcl-release, windows-mingw-release]
        
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Checkout vcpkg
      uses: actions/checkout@v4
      with:
        repository: microsoft/vcpkg
        path: vcpkg

    - name: Bootstrap vcpkg
      shell: cmd
      run: "${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh -disableMetrics"

    - name: Set VCPKG_ROOT
      shell: cmd
      run: echo "${{ github.workspace }}/vcpkg" >> "$VCPKG_ROOT"

    - name: Export GitHub Actions cache environment variables (for vcpkg)
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Set reusable strings
      id: strings
      shell: cmd
      run: echo "build-output-dir=${{ github.workspace }}/build/${{ matrix.preset }}" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }}
